### PR TITLE
docker: added cron container 

### PR DESCRIPTION
**Pull request by yodapotatofly**
Added a new container "cron" using official `docker` image.
-Has access to the docker socket
-Runs cron as a foreground process.
-Scripts are passed through a bind-mout

Added daily scripts for executing logrotate in Suricata container and pushing rules to suri in Scirius container ([see here](https://github.com/StamusNetworks/SELKS/pull/384/files?file-filters%5B%5D=.sh&show-viewed-files=true))

### CODE REVIEW

**Comment by yodapotatofly** [comment]
latest change actually doesn't work properly

**Comment by yodapotatofly** [comment]
> latest change actually doesn't work properly

Now it does :)

**Comment by pevma** [comment]
1 - remove and prune all dockers and folders before hand.
2 - test command
 
```
git clone -b cron  https://github.com/yodapotatofly/SELKS.git && cd SELKS/docker/
./easy-setup.sh  --non-interactive -i tppdummy0 --iA   &&  docker-compose up -d  ; \
sleep 180; ./scripts/readpcap.sh -c test.pcap
```

This is error-ing  in my tests :

```
Creating volume "selks_suricata-logrotate" with default driver
Creating scirius       ... done
Creating kibana        ... done
Creating evebox        ... done
Creating cron          ... done
Creating elasticsearch ... done
Creating nginx         ... done
Creating logstash      ... 
Creating suricata      ... error

Creating logstash      ... done
data, flags: 0x1000: no such file or directory

ERROR: for suricata  Cannot create container for service suricata: failed to mount local volume: mount /opt/hunt/SELKS/docker/containers-data/suricata/logrotate:/var/lib/docker/volumes/selks_suricata-logrotate/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.

real	1m33.003s
user	0m5.257s
sys	0m0.163s
Delete suricata logs:
OK

send SIGHUP to suricata:
Error response from daemon: Cannot kill container: suricata: No such container: suricata
ERROR

Delete elasticsearch indexes:
OK

Unable to find image 'jasonish/suricata:master' locally
master: Pulling from jasonish/suricata
Digest: sha256:35c93dd5fc4ccb960f577e7fd4548e7b3c4a7920b2af90f290dde5d892acc734
Status: Downloaded newer image for jasonish/suricata:master
Creating /etc/suricata/classification.config.
Creating /etc/suricata/reference.config.
Creating /etc/suricata/suricata.yaml.
Creating /etc/suricata/threshold.config.
Creating /etc/suricata/update.yaml.
suricata.yaml edited
Checking for capability sys_nice: yes

```

**Comment by yodapotatofly** [comment]
I always forgot that git doesn't keep empty folders -_-

**Comment by pevma** [comment]
Now i see it tries to pull the suricata container again , even though it was just pulled and build

```
Unable to find image 'jasonish/suricata:master' locally
master: Pulling from jasonish/suricata
Digest: sha256:35c93dd5fc4ccb960f577e7fd4548e7b3c4a7920b2af90f290dde5d892acc734
Status: Downloaded newer image for jasonish/suricata:master
include: selks6-addin.yaml
suricata.yaml edited
Checking for capability sys_nice: yes
Checking for capability net_admin: yes

```
Same test sequence  -shutdown and remove all containers, start and rebuild clean.

**Comment by pevma** [comment]
Needs rebase and probably a name check for the  suricata docker.

**Pull request merged**
