### PR TITLE
Fix elasticsearch-curator version in apt sources list. Add it to the upgrade script.

### LINKED ISSUE #142: [SELKS5] delete-old-logs.sh uses python 3.6, 3.5 latest stable version.
When I execute the /opt/selks/delete-old-logs.sh executable I receive the following error:

```
Traceback (most recent call last):
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run_singleton.py", line 24, in <module>
  File "/home/buh/curator/curator/__init__.py", line 6, in <module>
  File "/home/buh/curator/curator/utils.py", line 1, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/__init__.py", line 17, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/__init__.py", line 3, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 2, in <module>
  File "/usr/local/lib/python3.6/ssl.py", line 101, in <module>
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

The script points to python3.6 (Debian testing/unstable) but the latest version on SELKS5 is python3.5 (stable). We should either update to 3.6 or alter elastic-curator in a way that it uses version 3.5.

### PR DESCRIPTION
**Pull request by Jeroen0494**
The upgrade script didn't have the elasticsearch-curator package repo setup at all so I added it. This fixes #142.

### CODE REVIEW

**Comment by pevma** [comment]
Merged, thanks!

**Comment by Jeroen0494** [comment]
You're welcome! You can close the issue.

**Comment by aderumier** [comment]
@Jeroen0494 @pevma 

you have a typo in

cat >> /etc/apt/sources.list.d/curator5.list <<EOF
dev [arch=amd64] https://packages.elastic.co/curator/5/debian9 stable main
EOF

it's "deb [arch ..." , not "dev [arch ..."

**Comment by pevma** [comment]
Thanks!
Fixed - 
https://github.com/StamusNetworks/SELKS/commit/2d5e532486515fa751f3a814f097947a60f2b741

**Pull request merged**
