### PR TITLE
docker: ingest pcaps dirrectly in arkime

### PR DESCRIPTION
**Pull request by yodapotatofly**

### CODE REVIEW

**Comment by pevma** [comment]
It should also not import the pcaps produced by suricata , but directly the one passed on the command line.

**Comment by pevma** [comment]
Seems like an issue with `/readpcap` folder not being there when needed , might be cleaned up.

**Comment by yodapotatofly** [comment]
Sorry @pevma , I had not see your comments.
I believe your tests were not reflecting the commit since I made changes to the dockerfile, but the docker image is only built after changes are merged. Therefore you were probably not using the newer image.

You probably want to do this in your testing protocol :
```
docker build -t ghcr.io/stamusnetworks/arkimeviewer:local -f ./Arkime/Arkime.dockerfile ./Arkime
./easy-setup.sh --arkimeviewer-version local
```

This will build a "local" version of the image that is up-to-date with the changes

**Comment by pevma** [comment]
Awesome work, Thank you !

**Pull request merged**
